//! Raw FFI bindings to [mlx-c](https://github.com/ml-explore/mlx-c).
//!
//! Covers all of mlx-c: generated by bindgen from its umbrella header, with the
//! allowlist in `build/bindings.rs` trimming non-`mlx_*` symbols. Everything here
//! is `unsafe` to call; use the `mlx-rust` crate for the safe layer.

#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case)]
#![allow(dead_code, clippy::all)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

/// Absolute path of the `mlx.metallib` produced by this build.
///
/// MLX bakes this in as `METAL_PATH`; exposed for diagnostics.
#[cfg(feature = "metal")]
pub const METALLIB_PATH: &str = env!("MLX_RUST_METALLIB_PATH");
